name: 'Setup  Node + Install Dependencies'
description: 'Setup  Node + Install Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: 📦 Install Project Dependencies
      run: npm install
      shell: bash
